service: codenews

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: us-east-1

functions:
  posts:
    handler: handler.posts
    events:
      - http:
          path: posts
          method: get
          cors: true
      - http:
          path: posts
          method: post
          cors: true
      - http:
          path: posts
          method: delete
          cors: true
      - http:
          path: posts/draft
          method: post
          cors: true
      - http:
          path: posts/tags
          method: get
          cors: true
      - http:
          path: posts/tags
          method: post
          cors: true
  contributors:
    handler: handler.contributors
    events:
      - http:
          path: contributors
          method: get
          cors: true

plugins:
  - serverless-offline
