service: codenews

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: us-east-1

functions:
  posts:
    handler: handler.posts
    events:
      - http:
          path: posts
          method: get
          cors: true

plugins:
  - serverless-offline
